### ISSUE TITLE
Exception closing connection

### ISSUE THREAD

**Issue by jenstroeger** [nakagami/CyMySQL#12]
I'm running cymysql (0.8.5) and SQLAlchemy (0.9.8) for a MySQL db. When the web server (Python 3.4, pyramid 1.5.1) is inactive and just sitting for longer periods of time, I repeatedly see the following exception occur:

```
ERROR [sqlalchemy.pool.QueuePool][b'uWSGIWorker1Core0'] Exception closing connection <cymysql.connections.Connection object at 0x7fb2c969fef0>
Traceback (most recent call last):
  File "/var/www/.../lib64/python3.4/site-packages/sqlalchemy/pool.py", line 290, in _close_connection
    self._dialect.do_close(connection)
  File "/var/www/.../lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 426, in do_close
    dbapi_connection.close()
  File "/var/www/.../lib64/python3.4/site-packages/cymysql/connections.py", line 271, in close
    self.socket.sendall(send_data)
BrokenPipeError: [Errno 32] Broken pipe
```

Is this a problem? A configuration issue?

**Comment by nakagami** [comment]
Sorry driver can't avoid a broken pipe when the query takes too long.
