### ISSUE TITLE
cymysql.err.InternalError: (1043, 'Bad handshake')

### ISSUE THREAD

**Issue by youthantao** [nakagami/CyMySQL#22]
Server version: 5.5.56-MariaDB MariaDB Server

Traceback (most recent call last):
  File "D:/PycharmProjects/cymysqlTest/mm.py", line 3, in <module>
    conn = cymysql.connect(host='127.0.0.1',port=3306,user="root",passwd="1123",db="ssp",charset='utf8')
  File "C:\Users\Chin\venv\cymysqlTest\lib\cymysql\__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Chin\venv\cymysqlTest\lib\cymysql\connections.py", line 222, in __init__
    self._connect()
  File "C:\Users\Chin\venv\cymysqlTest\lib\cymysql\connections.py", line 388, in _connect
    self._request_authentication()
  File "C:\Users\Chin\venv\cymysqlTest\lib\cymysql\connections.py", line 460, in _request_authentication
    auth_packet = MysqlPacket(self)
  File "C:\Users\Chin\venv\cymysqlTest\lib\cymysql\packet.py", line 67, in __init__
    raise_mysql_exception(self.__data)
  File "C:\Users\Chin\venv\cymysqlTest\lib\cymysql\err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "C:\Users\Chin\venv\cymysqlTest\lib\cymysql\err.py", line 138, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
cymysql.err.InternalError: (1043, 'Bad handshake')

**Comment by nakagami** [comment]
Can you test with master branch on github repository ?
I hope to test with the latest version.

**Comment by betaxab** [comment]
@nakagami CyMysql still not worked on MySQL 5.6.16. I'm using the lastest submit 1e55459a25200e0fadea1cfe7a2ca838d7f0d505
Can you review it again?

**Comment by betaxab** [comment]
I confirmed this commit have a issue: f941eb3f7112f612b085bedc75fc9bdf17231608

**Comment by nakagami** [comment]
Thanks

Probably fix it, so please  retry with master HEAD.
Is it fixed ?

**Comment by youthantao** [comment]
Thanks. 
 It works ~
